# Generated by Django 4.2.9 on 2025-05-14 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('component_type', models.CharField(choices=[('kafka', 'Kafka'), ('mq', 'Message Queue'), ('db', 'Database'), ('service', 'Service'), ('api', 'API')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validation_mode', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('none', 'None')], default='optional', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('yaml_file_path', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partially_completed', 'Partially Completed')], default='pending', max_length=20)),
                ('validation_enabled', models.BooleanField(default=True)),
                ('execution_log', models.TextField(blank=True)),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_executions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflow.workflowdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('kafka_to_kafka', 'Kafka to Kafka Replay'), ('kafka_to_mq', 'Kafka to MQ Replay'), ('mq_to_mq', 'MQ to MQ Replay'), ('mq_to_kafka', 'MQ to Kafka Replay'), ('db_operation', 'DB Updates and Queries')], max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='workflow.workflowcomponent')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='workflow.workflowcomponent')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='workflow.workflowdefinition')),
            ],
        ),
        migrations.AddField(
            model_name='workflowcomponent',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='workflow.workflowdefinition'),
        ),
        migrations.CreateModel(
            name='RetryStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_type', models.CharField(choices=[('fixed', 'Fixed Interval'), ('exponential', 'Exponential Backoff'), ('custom', 'Custom Strategy')], max_length=20)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('initial_delay_seconds', models.PositiveIntegerField(default=5)),
                ('backoff_factor', models.FloatField(default=2.0, help_text='For exponential backoff strategy')),
                ('custom_strategy', models.TextField(blank=True, help_text='Custom retry logic in YAML format')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retry_strategies', to='workflow.workflowcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentExecutionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.workflowcomponent')),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_statuses', to='workflow.workflowexecution')),
            ],
        ),
    ]
