# Generated by Django 4.2.9 on 2025-05-17 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubWorkflowExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partially_completed', 'Partially Completed')], default='pending', max_length=20)),
                ('validation_enabled', models.BooleanField(default=True)),
                ('execution_log', models.TextField(blank=True)),
                ('include_start', models.BooleanField(default=True)),
                ('include_end', models.BooleanField(default=True)),
                ('end_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_workflow_ends', to='workflow.workflowcomponent')),
                ('parent_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_executions', to='workflow.workflowexecution')),
                ('start_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_workflow_starts', to='workflow.workflowcomponent')),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_workflow_executions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_executions', to='workflow.workflowdefinition')),
            ],
        ),
    ]
